version: "3.9"

services:
  web:
    build: .
    container_name: site_generator_web
    environment:
      - PANDASCORE_API_TOKEN=${PANDASCORE_API_TOKEN}
      - SITE_BASE_URL=${SITE_BASE_URL}
    expose:
      - "5000"
    networks:
      - site_net

  nginx:
    image: nginx:stable
    container_name: site_generator_nginx
    ports:
      - "42420:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - site_net

networks:
  site_net:
    driver: bridge